version: '3'

services:
  database:
    container_name: translatecard-api-db
    hostname: translatecard-api-postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    
  app:
    container_name: translatecard-api-app
    hostname: translatecard-api-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://user:password@database:5432/database
    command: tail -f /dev/null